- name: Reload Cisco Device
  hosts: myhosts
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Reload device
      cli_command:
        command: reload
        prompt:
          - Save?
          - confirm
        answer:
          - y
          - y
